### ISSUE TITLE
Map Overlays

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/isd-prioritization#7]
- Top 25 cities by population
- ISD FY16 Programming

**Comment by danbjoseph** [comment]
cities are done. i did most populated for top 15 ranked countries (top 20 had some bad looking overlap in the default load view)

@dalekunce what were you envisioning for the FY16 programming? toggle-able icon layer with icon on each country on the map with sectors in the tooltip? the info incorporated into the table? toggle-able border highlighting (small countries might look odd or be lost)?

**Comment by dalekunce** [comment]
yeah just a toggle-able icon to add the layer onto the map. I would maybe just do icons with more info in the rollover.

**Comment by danbjoseph** [comment]
done
